<?php

namespace app\controllers;
use app\models\Model;
use app\models\Shop;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\TestForm;


class PostController extends AppController {
public $layout = 'basic';

   public function beforeAction($action)
   {
       if ($action->id == 'index'){
           $this->enableCsrfValidation = false;
       }
       return parent::beforeAction($action); // TODO: Change the autogenerated stub
   }

    public function actionTest(){
        if(Yii::$app->request->isAjax){
            //debug($_GET);
            $this->debug(Yii::$app->request->post());
            return 'test';
        }
        $model = new TestForm();

        if ($model->load(Yii::$app->request->post()) ){
            if ($model -> validate()){
                Yii::$app->session->setFlash('success', 'данные приняты');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'error');
            }
        }

        return $this->render('test', compact('model'));
    }

    public function actionShow(){
       $this->view->title ='Одна статья';
       $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевики...']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'описание страницы...']);

        $cats = Shop::find()->all();

        return $this->render('show',compact('cats'));
    }
}